### ISSUE TITLE
Windows 11 - 22H2 updates not showing up in the list

### ISSUE THREAD

**Issue by JeeBee14** [OSDeploy/OSDUpdate#5]
I'm currently trying to automate my offline servicing for Windows 10 21H2 and Windows 11 22H2. All the Windows 10 updates I need are showing up as expected, but it seems as though I'm missing the Windows 11 22H2 LCUs. For example, the latest Windows 11 22H2 KB for July 2023 is not in the list: KB5028185. Am I the only seeing this issue?

**Comment by OSDeploy** [comment]
It's a mistake in the metadata I released.  It shows the old KBNumber, but if you look at the URL, it is the correct KB.  I'm unable to update today as I'm out today with a family doctor's appointment.

**Comment by JeeBee14** [comment]
Hi David, thanks for the reply. I still cannot find any Windows 11 LCUs specific to 22H2, not even from June or May. I've filtered the results from Get-OSDSUS using the URL and still cannot find the KB5028185. Am I missing or misunderstanding something?

**Comment by OSDeploy** [comment]
Ok, are you using this for OSDBuilder or OSDSUS?  If OSDSUS, the Windows 11
22H2 LCU is not included.  The reason why is Microsoft transitioned to an
UUP update which doesn't work the same as the previous CAB or MSU files and
I haven't sorted out how to work with those.  This also impacts WimWitch.

OSDBuilder doesn't use OSDSUS, it uses WSUSXML which is part of the OSD
Module.  That one contains the updated LCU which works properly.

Please detail how you are using this?

David Segura

**Comment by JeeBee14** [comment]
Oh I see! I basically need a way to automate the download of those updates in order to inject them in the wims I have in SCCM, since the built-in "Schedule Updates" feature doesn't work with Windows 11. I'll definitely look into the OSD Module! Thanks again David.
